name: FPCA AFT Health App
version: "0.1.0"
slug: fpca_aft_addon
description: FPCA and Weibull AFT survival model proof-of-concept app

startup: application
boot: auto
init: false

ingress: true
ingress_port: 5056

panel_icon: mdi:heart-pulse
panel_title: FPCA AFT Health
panel_admin: false

homeassistant_api: true
hassio_api: true

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.20
  amd64: ghcr.io/home-assistant/amd64-base:3.20
  armhf: ghcr.io/home-assistant/armhf-base:3.20
  armv7: ghcr.io/home-assistant/armv7-base:3.20
  i386: ghcr.io/home-assistant/i386-base:3.20

options:
  steps_entity_id: "sensor.nick_r_steps"
  timezone: "America/New_York"

  age: 50
  bmi: 27

  sex: "Male"
  race_ethnicity: "Non-Hispanic White"
  education: "College graduate+"
  marital_status: "Never married"
  smoking_status: "Never"

  alcohol_use: "Yes"

  hypertension: "No"
  diabetes: "No"
  heart_attack: "No"
  stroke: "No"
  cancer: "No"

  self_rated_health: "Very good"

schema:
  steps_entity_id: str
  timezone: str
  age: int
  bmi: float
  sex: list(Female|Male)
  race_ethnicity: list(Mexican American|Non-Hispanic Asian|Non-Hispanic Black|Non-Hispanic White|Other Hispanic|Other Race - Including Multi-Racial)
  education: list(less_than_9th_grade|9-11th grade|High school/GED|Some college/AA|College graduate+)
  marital_status: list(Divorced|Living with partner|Married|Never married|Separated|Widowed)
  smoking_status: list(Current|Former|Never)
  alcohol_use: list(No|Yes)
  hypertension: list(No|Yes)
  diabetes: list(No|Yes)
  heart_attack: list(No|Yes)
  stroke: list(No|Yes)
  cancer: list(No|Yes)
  self_rated_health: list(Excellent|Very good|Good|Fair|Poor)
